### ISSUE TITLE
Need to add python 3.7 for Gaudi

### ISSUE THREAD

**Issue by joequant** [key4hep/k4-spack#42]
need to add the following to key4hep-stack for gaudi

    # gaudi needs 3.7.99
    depends_on('python@:3.7.99')

Right now the dependencies I have for key4hep-stack

    # be explicit to avoid concretizer errors
    depends_on('root cxxstd=17 +root7 +ssl')
    depends_on('boost +python')
    depends_on('clhep cxxstd=17')
    # gaudi needs 3.7.99
    depends_on('python@:3.7.99')

**Comment by vvolkl** [comment]
Hi @joequant,

the python dependency of gaudi is declared in the gaudi recipe, where it should be: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/gaudi/package.py#L54 In principle, this should be enough to constrain the python version used for key4hep-stack. Can you document the error that prompted you to add this?

Regarding the other lines, you are working around a known issue in spack: https://spack.readthedocs.io/en/latest/known_issues.html#variants-are-not-properly-forwarded-to-dependencies
Thomas and I also tried to document the possible fixes here: https://key4hep.github.io/key4hep-doc/spack-build-instructions/spack-advanced.html#working-around-spack-concretizer-problems
#31 includes a `packages.yaml` that should fix all concretizer errors - you'll notice the variants for boost and clhep are already in there. I prefer to use config files instead of dependency declaration, if there is no real dependency, but if it makes it easier, we can also add them as dependencies to key4hep-stack.

**Comment by andresailer** [comment]
I think the problem is that the spack default python was changed to 3.8 a few days ago, but gaudi doesn't allow this yet.
```
gaudi requires python version :3.7.99, but spec asked for 3.8.5
```
https://github.com/spack/spack/commit/6fcec1dcff50168cf4534eb1fd23a73ad08ef472

This is either an issue with the gaudi recipe, or we need to specify our own preferred python version.
